{
  "name": "example",
  "type": "Example",
  "description": "autogenerated",
  "__proto": {
    "package": "example",
    "options": {},
    "imports": [],
    "targetfile": "example.proto"
  },
  "fields": {
    "id": {
        "description": "Identity of Example",
        "type": "string",
        "meta": {
          "label": "Id",
          "default": "",
          "hint": ""
        },
        "constraints": {},
        "__proto": {
          "number": 1
        }
    },
    "display_name": {
      "description": "Localized String representation of a Example",
      "type": "string",
      "meta": {
        "label": "Example",
        "default": "",
        "hint": "",
        "readonly": true
      },
      "constraints": {},
      "__proto": {
        "number": 2
      }
    }

  }
}
